maha_dbt:
  outputs:

    dev:
      type: databricks
      catalog: dbt_tuto_dev
      host: "{{ env_var('DBT_HOST', 'dbc-264bc18d-40a0.cloud.databricks.com') }}"
      http_path: "{{ env_var('DBT_HTTP_PATH', '/sql/1.0/warehouses/485609dd966489d5') }}"
      token: "{{ env_var('DBT_TOKEN') }}"
      schema: default
      threads: 2

    prod:
      type: databricks
      catalog: "{{ env_var('DBT_PROD_CATALOG', 'dbt_tuto_prod') }}"
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DBT_HTTP_PATH') }}"
      token: "{{ env_var('DBT_TOKEN') }}"
      schema: default
      threads: 8

  target: dev
